# Nothing generated is edited by hand, and build_theme() is idempotent -- which is the only reason
# `check = TRUE` means anything. It holds because no banner carries a date and every key is sorted.

test_that("the two copies of the pandoc theme are one file", {
  skip_without_source()
  expect_identical(
    readLines(file.path(src_root(), "inst/highlight/txtheme-dark.theme"), warn = FALSE),
    readLines(file.path(src_root(), "_extensions/txtheme/txtheme-dark.theme"), warn = FALSE))
})

test_that("every generated file is in step with the grids", {
  skip_without_source()
  expect_true(build_theme(src_root(), check = TRUE, quiet = TRUE))
})

test_that("every generated file says so on its first line, and every hand-written one says PURPOSE", {
  skip_without_source()
  gen <- names(txtheme:::tx_outputs(src_root()))
  for (f in gen) {
    # JSON has no comment syntax, so a .theme / .json banner rides in a `_comments` key -- three
    # lines in rather than one, which is as close to "the first line" as the format allows.
    head3 <- paste(readLines(file.path(src_root(), f), n = 3L), collapse = " ")
    expect_match(head3, "GENERATED by txtheme::build_theme", fixed = TRUE, info = f)
  }
  hand <- c("inst/prose/annotations.scss", "inst/pkgdown/BS5/assets/txtheme-at.js",
            "inst/pkgdown/BS5/templates/in-header.html", "_extensions/txtheme/_extension.yml")
  for (f in hand)
    expect_match(paste(readLines(file.path(src_root(), f), n = 3L), collapse = " "),
                 "PURPOSE", fixed = TRUE, info = f)
})

test_that("the pkgdown layer compiles, and carries the -rgb twins pkgdown reads", {
  skip_if_not_installed("sass")
  css <- as.character(sass::sass(sass::sass_file(txtheme_file("pkgdown/BS5/extra.scss"))))
  expect_match(css, "--bs-body-color-rgb: 205,203,188", fixed = TRUE)
  expect_match(css, "--bs-link-color-rgb: 97,175,239", fixed = TRUE)
  expect_match(css, "rgba(205,203,188,0.75)", fixed = TRUE)
  # 30 token classes plus `pre code` for Normal, all scoped so they out-specify pkgdown's theme-dark
  expect_equal(lengths(regmatches(css, gregexpr('pre code span\\.', css))), 30L)
})

test_that("the pandoc theme is valid JSON with skylighting's own 31 tokens", {
  txt <- paste(readLines(txtheme_file("highlight/txtheme-dark.theme"), warn = FALSE),
               collapse = "\n")
  for (k in c("text-color", "background-color", "line-number-color", "text-styles"))
    expect_match(txt, paste0('"', k, '"'), fixed = TRUE)
  expect_equal(length(gregexpr('"underline":', txt)[[1]]), 31L)
})

test_that("the flat highlight sheet parses as the pkgdown-bundled shape it imitates", {
  txt   <- paste(readLines(txtheme_file("highlight/txtheme-dark.scss"), warn = FALSE), collapse = "\n")
  txt   <- gsub("/\\*.*?\\*/", "", txt)                 # what tabxplor's preview does first
  rules <- regmatches(txt, gregexpr("[^{}]+\\{[^{}]*\\}", txt))[[1]]
  expect_equal(length(rules), 32L)                      # pre + pre code + 30 spans
  expect_true(all(grepl("^\\s*(pre|pre code)", rules)))
})

test_that("the brand file quotes every hex and names no colour after a role", {
  y <- readLines(txtheme_file("brand/_brand.yml"), warn = FALSE)
  from  <- which(y == "  palette:") + 1L
  to    <- which(grepl("^  [a-z]+:$", y) & seq_along(y) > from)
  block <- y[seq(from, if (length(to)) to[1] - 1L else length(y))]
  expect_true(all(grepl(': "#[0-9A-Fa-f]{6}"$', block)))    # unquoted, `#` would open a comment
  expect_length(intersect(sub("^ +([a-z0-9-]+):.*$", "\\1", block), txtheme:::BRAND_ROLES), 0L)
})
