# PURPOSE: the ONE generator. Everything under inst/ and _extensions/ that a consumer reads is
#   written here, from R/aaa-palette.R and nothing else.
# ROLE: run by hand when a colour changes -- never at render time, and never by a consumer's CI.
# KEY CONSTRAINTS:
#   - VALIDATE, THEN WRITE. The grids' own foreign keys run first (tx_check_grids()), then the
#     contrast report, which is where a colour's readability is MEASURED instead of recorded: a slot
#     knows the ground it is read on, a colour does not, so |Lc| belongs to this stage and not to a
#     cell in TX_PALETTE.
#   - IDEMPOTENT BY CONSTRUCTION, which is what makes `check = TRUE` a real test: no dates in any
#     banner, sorted keys in the JSON and the YAML, grid order everywhere else.
#   - A file's FIRST LINE says which side of the line it is on. Generated: "GENERATED by
#     txtheme::build_theme()". Hand-written: "PURPOSE:". There is no third kind.
# See: R/emit-*.R for the writers, dev/design.md section 7 for what each output is for.

#' Where a shipped txtheme file lives
#'
#' @param ... Path parts under the package's `inst/`, e.g. `"pkgdown/BS5/extra.scss"`.
#' @return An absolute path. Errors if the file is not there.
#' @examples
#' txtheme_file("highlight/txtheme-dark.scss")
#' @export
txtheme_file <- function(...) {
  p <- system.file(..., package = "txtheme")
  if (!nzchar(p)) stop("txtheme: no shipped file at ", file.path(...))
  p
}

#' Copy the brand file into a Quarto project
#'
#' Puts `_brand.yml` at `dir`. A Quarto project auto-discovers a `_brand.yml` at its root, so
#' nothing else is written and no `brand:` key is needed anywhere.
#'
#' @param dir The project root. Defaults to the working directory.
#' @param single_mode Copy `_brand-dark.yml` instead -- the shape `brand.yml`'s R side can parse,
#'   named explicitly as `brand: {dark: _brand-dark.yml}`.
#' @return The path written, invisibly.
#' @examples
#' use_brand(tempdir())
#' @export
use_brand <- function(dir = ".", single_mode = FALSE) {
  from <- txtheme_file(if (single_mode) "brand/_brand-dark.yml" else "brand/_brand.yml")
  to   <- file.path(dir, basename(from))
  file.copy(from, to, overwrite = TRUE)
  message("written: ", to,
          if (!single_mode) "  -- a Quarto project root discovers it with no YAML at all")
  invisible(to)
}

# What the generator writes, and where. A named list of path -> lines, built once so `check = TRUE`
# and the real write share every byte of their logic.
tx_outputs <- function(path = ".") {
  prose <- readLines(file.path(path, "inst", "prose", "annotations.scss"), warn = FALSE)
  modes <- c("dark", if (tx_has_mode("light")) "light")

  out <- list(
    "inst/pkgdown/BS5/extra.scss"                   = emit_extra_scss(),
    "inst/pkgdown/BS5/assets/txtheme-annotations.css" = emit_annotations_css(prose),
    "inst/brand/_brand.yml"                         = emit_brand_unified(),
    "inst/brand/_brand-dark.yml"                    = emit_brand_single("dark"),
    "inst/editor/token-colors.json"                 = emit_editor_json("dark"))

  # The .theme is written TWICE on purpose, and it is one emitter either way: `_extensions/` is
  # .Rbuildignore'd (a Quarto user gets it with `quarto add`, never from the R library), while the
  # copy under inst/ is what an R-side consumer reaches -- rmarkdown and bookdown take a file path
  # in `highlight:`, which is the only way a bookdown page can have this code theme at all.
  for (m in modes) {
    out[[paste0("inst/highlight/txtheme-", m, ".scss")]]       <- emit_highlight_scss(m)
    out[[paste0("inst/highlight/txtheme-", m, ".theme")]]      <- emit_pandoc_theme(m)
    out[[paste0("_extensions/txtheme/txtheme-", m, ".scss")]]  <- emit_quarto_scss(m)
    out[[paste0("_extensions/txtheme/txtheme-", m, ".theme")]] <- emit_pandoc_theme(m)
  }
  # WARNING: unname() is load-bearing. writeLines() drops names, so a named emitter result and the
  # readLines() of its own file are never identical() -- `check = TRUE` would report a file stale
  # forever, with no visible difference at all.
  lapply(out, unname)
}

# The check the recorded-apca column would have been, done properly: a slot knows its ground.
# Lc 90 fluent body text / 75 body columns / 60 content / 45 headlines / 30 spot-readable.
tx_contrast_report <- function(mode = "dark") {
  rows <- Filter(function(s) !tx_empty(s$ground), TX_SLOTS)
  data.frame(
    slot   = names(rows),
    colour = vapply(rows, function(s) s$colour, character(1)),
    on     = vapply(rows, function(s) s$ground, character(1)),
    Lc     = vapply(rows, function(s)
                abs(apca(tx_hex(s$colour, mode), tx_hex(s$ground, mode))), numeric(1)),
    row.names = NULL, stringsAsFactors = FALSE)
}

#' Regenerate every theme artifact
#'
#' Validates the grids, then writes the pkgdown layer, the flat highlight sheets, the Quarto
#' `.scss` / `.theme` pairs, the two brand files, the annotations asset and the editor block. Run it
#' by hand whenever a colour changes; never at render time.
#'
#' @param path The package root.
#' @param check Do not write: rebuild every output in memory and compare it with the file on disk.
#'   `TRUE` when they all match. This is what the test suite asserts, and it is only meaningful
#'   because nothing generated carries a date.
#' @param quiet Suppress the per-file message and the contrast report.
#' @return Invisibly, `TRUE` if everything is in step (always `TRUE` after a write).
#' @examples
#' \dontrun{
#' build_theme("~/github/txtheme")
#' build_theme("~/github/txtheme", check = TRUE)
#' }
#' @export
build_theme <- function(path = ".", check = FALSE, quiet = FALSE) {
  tx_check_grids()
  out <- tx_outputs(path)

  if (!quiet) {
    r <- tx_contrast_report("dark")
    message("contrast, dark (APCA |Lc|):")
    message(paste0("  ", formatC(r$slot, width = 18, flag = "-"), " ",
                   formatC(r$colour, width = 14, flag = "-"), " on ",
                   formatC(r$on, width = 6, flag = "-"), " ",
                   formatC(r$Lc, format = "f", digits = 1, width = 5), collapse = "\n"))
  }

  ok <- TRUE
  for (f in names(out)) {
    dest <- file.path(path, f)
    if (check) {
      same <- file.exists(dest) && identical(readLines(dest, warn = FALSE), out[[f]])
      if (!same) { ok <- FALSE; message("STALE: ", f) }
    } else {
      dir.create(dirname(dest), recursive = TRUE, showWarnings = FALSE)
      writeLines(out[[f]], dest)
      if (!quiet) message("written: ", f)
    }
  }
  if (check && ok && !quiet) message("every generated file is in step with R/aaa-palette.R")
  invisible(ok)
}
