# PURPOSE: the stylesheet writers -- the pkgdown layer, the flat highlight sheet, the Quarto pair,
#   and the annotations asset.
# ROLE: one small writer per output kind, all reading the four grids and nothing else.
# KEY CONSTRAINTS:
#   - ONE LINE PER RULE, always, and a rule is written where its declarations come from more than one
#     grid row too. That single formatting rule is what makes the output diffable and the
#     idempotence check meaningful.
#   - The dark cascade is prefixed `html[data-bs-theme="dark"]`, the light one is not: LIGHT IS A
#     MODE ARGUMENT, NOT A SECOND WRITER. Today no colour declares a `light` value, so the light
#     half is empty and pkgdown's own is what a light page gets.
#   - No dates in any banner. A generated file must be reproducible byte for byte, which is what
#     build_theme(check = TRUE) tests.
# See: R/build-theme.R for the stage list, R/aaa-palette.R for the grids.

DARK_PREFIX <- 'html[data-bs-theme="dark"]'

# The banner every generated file opens with. `comment` is "//" for scss, "/*" for a css/scss file
# something else PARSES -- the flat highlight sheet is read back by tabxplor's preview tool, whose
# splitter strips /* */ and would swallow a // line into the first selector.
tx_banner <- function(what, style = c("//", "/*")) {
  style <- match.arg(style)
  txt <- c("GENERATED by txtheme::build_theme() from R/aaa-palette.R -- do not edit.", what)
  mark <- if (style == "//") c("// ", "// ") else c("/* ", "   ")
  out  <- paste0(c(mark[1], rep(mark[2], length(txt) - 1L)), txt)
  out  <- sub(" +$", "", out)                       # no trailing space on a spacer line
  if (style == "//") out else c(out, "   */")
}

# The hex a colour shows in one mode. NA where the mode has no value -- which is how a light half
# that has not been decided yet stays empty rather than becoming a guess.
tx_hex <- function(colour, mode = "dark") {
  row <- TX_PALETTE[[colour]]
  if (is.null(row)) stop("txtheme: no colour named '", colour, "'")
  v <- row[[mode]]
  if (tx_empty(v)) NA_character_ else v
}

# What a slot writes as a value: the hex, or the hex at an opacity. rgba() and not an 8-digit hex,
# because bootstrap writes its own derived colours that way and one form beats two.
tx_value <- function(slot, mode = "dark") {
  hex <- tx_hex(slot$colour, mode)
  if (is.na(hex)) return(NA_character_)
  if (tx_empty(slot$alpha)) hex
  else sprintf("rgba(%s,%s)", hex_rgb(hex), format(slot$alpha, trim = TRUE))
}

tx_has_mode <- function(mode) any(!is.na(vapply(names(TX_PALETTE), tx_hex, character(1), mode = mode)))

# --- the four sections ----------------------------------------------------------------------------

tx_chrome_decls <- function(mode = "dark") {
  out <- character(0)
  for (s in tx_where(TX_SLOTS, "emit", "chrome")) {
    v <- tx_value(s, mode)
    if (is.na(v)) next
    out <- c(out, sprintf("%s: %s;", s$bs_var, v))
    if (!tx_empty(s$bs_rgb)) out <- c(out, sprintf("%s: %s;", s$bs_rgb, hex_rgb(tx_hex(s$colour, mode))))
  }
  out
}

# Slot rows folded into rules: one rule per selector, in first-appearance order, carrying every
# declaration the rows that name it asked for. A selector naming several elements ("strong, b") is
# written as it stands -- Sass prefixes each part.
tx_selector_rules <- function(stage, mode = "dark") {
  rows <- tx_where(TX_SLOTS, "emit", stage)
  sel  <- vapply(rows, function(r) r$selector, character(1))
  vapply(unique(sel), function(k) {
    decls <- character(0)
    for (r in rows[sel == k]) {
      v <- tx_value(r, mode)
      if (is.na(v)) next
      decls <- c(decls, sprintf("%s: %s;", r$prop, v))
      if (!tx_empty(r$style)) decls <- c(decls, paste0(sub(";\\s*$", "", r$style), ";"))
    }
    if (!length(decls)) "" else sprintf("%s { %s }", k, paste(decls, collapse = " "))
  }, character(1), USE.NAMES = FALSE)
}

# Ordered by pkgdown's two-letter CLASS, with Normal (`pre code`) first -- the order pkgdown's own
# 35 bundled styles are written in, so a diff against one of them reads straight down.
tx_tokens_by_class <- function() {
  cls <- tx_field(TX_TOKENS, "class")
  names(TX_TOKENS)[order(!is.na(cls), cls)]
}

tx_token_rules <- function(mode = "dark") {
  vapply(tx_tokens_by_class(), function(nm) {
    t <- TX_TOKENS[[nm]]
    v <- tx_hex(t$colour, mode)
    if (is.na(v)) return("")
    sel <- if (tx_empty(t$class)) "pre code" else paste0("pre code span.", t$class)
    dec <- paste0("color: ", v, ";")
    if (!tx_empty(t$style)) dec <- paste(dec, paste0(sub(";\\s*$", "", t$style), ";"))
    sprintf("%s { %s }", sel, dec)
  }, character(1), USE.NAMES = FALSE)
}

tx_drop_empty <- function(x) x[nzchar(x)]

# --- the pkgdown layer ----------------------------------------------------------------------------

# WARNING: this is the file pkgdown reads as `template: package: txtheme`, and it arrives as a RULES
#   layer (bslib::bs_add_rules), landing at the very end of the compiled CSS. A Sass VARIABLE set
#   here would be inert; a bootstrap 5.3 custom property is not, and all eight chrome targets have
#   `--bs-*` twins -- which is the whole reason this package needs no brand file and no bslib: block.
emit_extra_scss <- function() {
  body <- function(mode) c(
    "// the chrome -- bootstrap 5.3's colour-mode properties, plus the `-rgb` twins it derives from",
    tx_chrome_decls(mode), "",
    "// the heading ladder", tx_drop_empty(tx_selector_rules("heading", mode)), "",
    "// prose -- what the editor theme colours in markdown, and bootstrap has no variable for",
    tx_drop_empty(tx_selector_rules("prose", mode)), "",
    "// the code theme -- skylighting's 31 tokens, ported from izumii.starless-monokai",
    tx_drop_empty(tx_token_rules(mode)))

  light <- if (tx_has_mode("light")) c(
    ":root {", paste0("  ", tx_chrome_decls("light")), "}", "",
    tx_drop_empty(c(tx_selector_rules("heading", "light"), tx_selector_rules("prose", "light"),
                    tx_token_rules("light"))), "")

  c(tx_banner(c(
      "",
      "The pkgdown layer: the dark chrome, the heading ladder, prose, and the code theme.",
      "A consumer's whole _pkgdown.yml is `template: {bootstrap: 5, light-switch: true,",
      "package: txtheme}` -- there is no bslib: block and no brand file to copy.",
      "",
      "WARNING: `light-switch: true` is load-bearing. Every rule below is scoped",
      "  html[data-bs-theme=\"dark\"], and pkgdown only emits the dark cascade when the switch is on",
      "  -- so without it nothing here ever matches, silently and with no error.",
      "WARNING: the `html` in that prefix is not decoration. pkgdown appends its own theme-dark",
      "  block AFTER this file, so source order cannot win; only the extra element out-specifies it",
      "  (0,2,4 against 0,2,3).")),
    "", light,
    paste0(DARK_PREFIX, " {"),
    ifelse(nzchar(body("dark")), paste0("  ", body("dark")), ""),
    "}")
}

# --- the flat highlight sheet ---------------------------------------------------------------------

# The shape pkgdown bundles its own 35 styles in: flat, one line per token, the token's name in an
# aligned comment. That is what a site naming a style instead of taking the package would copy, and
# what tabxplor's dev/site_theme_preview.R reads back.
emit_highlight_scss <- function(mode = "dark") {
  toks <- tx_tokens_by_class()
  sel  <- vapply(toks, function(nm) {
    cl <- TX_TOKENS[[nm]]$class
    if (tx_empty(cl)) "pre code" else paste0("pre code span.", cl)
  }, character(1))
  dec <- vapply(toks, function(nm) {
    t <- TX_TOKENS[[nm]]
    v <- tx_hex(t$colour, mode)
    if (is.na(v)) return(NA_character_)
    if (tx_empty(t$style)) paste0("color:", v) else paste0("color:", v, "; ", sub(";\\s*$", "", t$style))
  }, character(1))
  keep <- !is.na(dec)
  ground <- tx_hex("code-page", mode)
  c(tx_banner(c("", paste0("The ", mode, " code theme, in pkgdown's own bundled shape."),
                "Copy it to pkgdown/extra.scss -- or take `template: package: txtheme`, which is that copy",
                "done by the toolchain."), style = "/*"),
    "",
    if (!is.na(ground)) sprintf("pre {background-color: %s}", ground),
    sprintf("%s /* %s */ {%s}",
            formatC(sel[keep], width = max(nchar(sel)), flag = "-"),
            formatC(toks[keep], width = max(nchar(toks)), flag = "-"), dec[keep]))
}

# --- the Quarto pair ------------------------------------------------------------------------------

# Quarto compiles bootstrap PROPERLY -- from Sass variables, not from a rules layer -- so the chrome
# is `$body-bg` and friends and there is no `-rgb` trap here: bootstrap derives every twin itself.
emit_quarto_scss <- function(mode = "dark") {
  defaults <- character(0)
  for (s in tx_where(TX_SLOTS, "emit", "chrome")) {
    if (tx_empty(s$sass_var)) next
    v <- tx_value(s, mode)
    if (!is.na(v)) defaults <- c(defaults, sprintf("%s: %s;", s$sass_var, v))
  }
  rules <- tx_drop_empty(c(tx_selector_rules("heading", mode), tx_selector_rules("prose", mode)))
  c(tx_banner(c("", paste0("The ", mode, " half of the Quarto theme, contributed by _extensions/txtheme."),
                "Chrome as bootstrap SASS VARIABLES: unlike pkgdown, Quarto compiles bootstrap from",
                "them, so the derived colours and every `-rgb` twin follow on their own."),
              style = "/*"),
    "", "/*-- scss:defaults --*/", defaults,
    "", "/*-- scss:rules --*/", rules)
}

# --- the annotations asset ------------------------------------------------------------------------

# OPT-IN, and never spliced into extra.scss. pkgdown.scss styles `pre code .error, pre code .warning`
# and a built reference page really does emit <span class="warning"> for an example's warning -- so
# `.non, .error {text-decoration: underline double}` in the site-wide layer would decorate every
# warned example on the site. A consumer asks for it with
# `template: params: {txtheme: {annotations: true}}`.
emit_annotations_css <- function(prose, mode = "dark") {
  vars <- vapply(tx_where(TX_SLOTS, "emit", "annotation"), function(s) {
    v <- tx_value(s, mode); if (is.na(v)) NA_character_ else sprintf("  %s: %s;", s$css_var, v)
  }, character(1), USE.NAMES = FALSE)
  c(tx_banner(c("", "The twelve pandoc-span annotation classes: their colours from TX_PALETTE, their",
                "typography from inst/prose/annotations.scss, appended below unchanged."),
              style = "/*"),
    "", ":root {", vars[!is.na(vars)], "}", "", prose)
}
