# PURPOSE: the `_brand.yml` writers -- the unified light/dark file Quarto auto-discovers, and the
#   single-mode one for the explicit `brand: {light:, dark:}` form.
# ROLE: layer A's artifact. It is what makes the palette readable by something that is not a
#   stylesheet -- a Quarto project, brand.yml's R side, or the next tool that learns the format.
# KEY CONSTRAINTS:
#   - Hand-rolled YAML, ~15 lines, for the same reason as the JSON (see R/aaa-grid.R). EVERY hex is
#     quoted: `#` opens a comment in YAML, so an unquoted colour is silently the empty string.
#   - The unified file is the primary artifact and needs NO `brand:` key from the consumer -- Quarto
#     auto-discovers a `_brand.yml` at a project root. An extension CANNOT set `brand:` for its
#     consumer (that key is resolved from project/document metadata, not from a format's render
#     defaults), so a file at the root is not a fallback here, it is the mechanism.
#   - A role is written for the modes that HAVE a value, and Quarto correctly ignores a role in the
#     mode it does not name -- measured on 1.10.18: `background: {dark: page}` leaves the light
#     stylesheet on #ffffff. So a half-stated role is safe, and the light half of this file appears
#     the day TX_PALETTE's `light` column is filled in, with no change here.
#   - THE PALETTE'S NAMES ARE A NAMESPACE QUARTO SHARES. A `color.palette` entry named after a brand
#     ROLE is promoted to that role, in BOTH modes and with no message. R/zzz-checks.R refuses such
#     a name at load; the colour that paints links is called `accent` for exactly this reason.
# See: R/aaa-palette.R for TX_BRAND and BRAND_ROLES, dev/design.md sections 2-3 for what each
#   consumer reads.

tx_yaml_hex <- function(x) paste0('"', x, '"')

# The palette Quarto's `brand.color.palette` holds: every colour we have a name for, so a document
# can say `brand.color.palette.gold` without the hex leaving this package.
tx_brand_palette <- function(mode) {
  nms <- names(TX_PALETTE)
  hex <- vapply(nms, tx_hex, character(1), mode = mode)
  nms <- nms[!is.na(hex)]; hex <- hex[!is.na(hex)]
  paste0("    ", nms, ": ", tx_yaml_hex(hex))
}

#' The unified brand file
#'
#' One `_brand.yml`, per-colour `{light:, dark:}` -- the shape Quarto auto-discovers at a project
#' root with no YAML at all on the consumer's part.
#'
#' @param modes The halves to write. A mode with no colours contributes nothing.
#' @return A character vector of lines.
#' @noRd
emit_brand_unified <- function(modes = c("light", "dark")) {
  have  <- modes[vapply(modes, tx_has_mode, logical(1))]
  roles <- unlist(lapply(names(TX_BRAND), function(k)
    c(paste0("  ", k, ":"), paste0("    ", have, ": ", TX_BRAND[[k]]$colour))))
  c("# GENERATED by txtheme::build_theme() from R/aaa-palette.R -- do not edit.",
    "#",
    "# The unified brand: one file, a light and a dark value per role. Copy it to a Quarto project's",
    "# ROOT and write nothing -- `brand:` is auto-discovered from there. It must never sit under",
    "# `format: html:`; nested there it is silently ignored, the two stylesheets come out identical,",
    "# and none of these colours appear.",
    "#",
    "# Only the dark half of the palette is decided, so only `dark:` is written under each role.",
    "# That is safe, not a compromise: measured on Quarto 1.10.18, a role names a mode or is ignored",
    "# in it -- `background: {dark: page}` leaves the light stylesheet on #ffffff.",
    "#",
    "# WARNING: the palette's NAMES share a namespace with the roles. An entry named after a role",
    "#   (link, primary, danger, ...) is promoted to that role in BOTH modes, silently -- which is",
    "#   why the blue below is `accent` and not `link`. txtheme refuses such a name at load.",
    "#",
    "# The palette also reaches BOTH stylesheets as `--brand-<name>` custom properties, so a document",
    "# can use any of these colours by name without a hex leaving txtheme.",
    "meta:",
    "  name: txtheme",
    "color:",
    "  palette:",
    tx_brand_palette("dark"),
    roles)
}

#' The single-mode brand file
#'
#' The shape `brand.yml::read_brand_yml()` can actually parse: the R side of the spec rejects
#' `color.foreground: {light:, dark:}`, so a tool reading a brand file from R needs one file per
#' mode. Quarto reads it too, named explicitly under `brand: {dark: …}`.
#'
#' @inheritParams emit_brand_unified
#' @return A character vector of lines.
#' @noRd
emit_brand_single <- function(mode = "dark") {
  roles <- vapply(names(TX_BRAND), function(k)
    paste0("  ", k, ": ", TX_BRAND[[k]]$colour), character(1))
  c("# GENERATED by txtheme::build_theme() from R/aaa-palette.R -- do not edit.",
    "#",
    paste0("# The ", mode, " half alone. Use this one where a reader cannot take `{light:, dark:}`:"),
    "# brand.yml's R side rejects that shape, and Quarto takes it named explicitly, as",
    paste0("# `brand: {", mode, ": _brand-", mode, ".yml}`. inst/brand/_brand.yml is the file to prefer."),
    "meta:",
    "  name: txtheme",
    "color:",
    "  palette:",
    tx_brand_palette(mode),
    roles)
}
