# PURPOSE: the pandoc `.theme` writer, and the two JSON primitives it and the editor writer share.
# ROLE: the Quarto half of layer B -- the same 31 tokens the pkgdown `.scss` carries, in pandoc's own
#   vocabulary. One grid generates both, which is the point of TX_TOKENS.
# KEY CONSTRAINTS:
#   - Hand-rolled JSON, ~20 lines, rather than a jsonlite dependency: the shapes are small, known and
#     ours, and a theme package must install anywhere (see R/aaa-grid.R). tx_json_str() REFUSES a
#     string it cannot write instead of writing a broken file.
#   - Keys are sorted, so the output is reproducible byte for byte and build_theme(check = TRUE)
#     means something.
#   - pandoc's `.theme` has four top-level scalars plus `text-styles`. `_comments` is accepted
#     (pandoc's own a11y-dark carries one) and is where the banner goes, JSON having no comments.

tx_json_str <- function(x) {
  x <- as.character(x)
  if (any(grepl('[\\"[:cntrl:]]', x)))
    stop("txtheme: a JSON string holds a quote, a backslash or a control character: ", x[1])
  paste0('"', x, '"')
}

# A named list to JSON, two levels of nesting deep -- all these files need. NULL is written `null`,
# a logical `true`/`false`, an unnamed list an array.
tx_json <- function(x, indent = 0L) {
  pad <- strrep("    ", indent)
  if (is.null(x)) return("null")
  if (is.logical(x) && length(x) == 1L && !is.na(x)) return(if (x) "true" else "false")
  if (!is.list(x)) {
    if (length(x) == 1L) return(tx_json_str(x))
    return(paste0("[", paste(tx_json_str(x), collapse = ", "), "]"))
  }
  if (is.null(names(x))) {
    inner <- vapply(x, tx_json, character(1), indent = indent + 1L)
    return(paste0("[\n", paste0(pad, "    ", inner, collapse = ",\n"), "\n", pad, "]"))
  }
  inner <- vapply(seq_along(x), function(i)
    paste0(pad, "    ", tx_json_str(names(x)[i]), ": ", tx_json(x[[i]], indent + 1L)), character(1))
  paste0("{\n", paste(inner, collapse = ",\n"), "\n", pad, "}")
}

# Read a style back out of the CSS a grid row writes, so the three backends cannot disagree about
# what "bold" means: the declaration is the fact, bold/italic/underline are readings of it.
tx_style_flag <- function(style, what) {
  if (tx_empty(style)) return(FALSE)
  grepl(switch(what, bold = "font-weight: *bold", italic = "font-style: *italic",
               underline = "text-decoration: *underline"), style)
}

emit_pandoc_theme <- function(mode = "dark") {
  styles <- lapply(sort(names(TX_TOKENS)), function(nm) {
    t <- TX_TOKENS[[nm]]
    hex <- tx_hex(t$colour, mode)
    list("text-color" = if (is.na(hex)) NULL else hex,
         "background-color" = NULL,
         bold      = tx_style_flag(t$style, "bold"),
         italic    = tx_style_flag(t$style, "italic"),
         underline = tx_style_flag(t$style, "underline"))
  })
  names(styles) <- sort(names(TX_TOKENS))

  ground <- tx_hex("code-page", mode)
  out <- list(
    "_comments" = list(
      "GENERATED by txtheme::build_theme() from R/aaa-palette.R -- do not edit.",
      paste0("The ", mode, " code theme, for Quarto's `syntax-highlighting:`. The same 31 tokens as ",
             "inst/highlight/txtheme-", mode, ".scss, in pandoc's vocabulary instead of pkgdown's.")),
    "text-color" = tx_hex("ink", mode),
    "background-color" = if (is.na(ground)) NULL else ground,
    "line-number-color" = tx_hex("comment", mode),
    "line-number-background-color" = if (is.na(ground)) NULL else ground,
    "text-styles" = styles)
  strsplit(tx_json(out), "\n", fixed = TRUE)[[1]]
}
