# PURPOSE: the editor block -- a ready `textMateRules` array to paste under
#   `editor.tokenColorCustomizations` in Positron / VS Code.
# ROLE: the third consumer of the same TX_TOKENS grid, so a hex is written in one place and reaches
#   the site and the editor by the same generator.
# KEY CONSTRAINTS:
#   - It NECESSARILY ends in a manual paste. `editor.tokenColorCustomizations` has no include
#     mechanism -- VS Code settings cannot reference a file -- so the editor side is a paste (or a
#     synced profile) whatever the repository layout is. That is also why txtheme does not try to be
#     an editor extension: see dev/design.md section 5.1.
#   - Rows are GROUPED by (colour, style) and their scopes unioned, so a colour is one rule rather
#     than eleven. Unstyled groups are written first and styled ones last, because a scope can
#     legitimately appear in both (`comment` is plain for Annotation and italic for Comment) and in
#     TextMate the later rule wins -- which is the reading the editor theme itself gives.
# See: R/emit-theme.R for the JSON primitives, R/aaa-palette.R for TX_TOKENS.

emit_editor_json <- function(mode = "dark") {
  toks  <- Filter(function(t) !tx_empty(t$tm_scope), TX_TOKENS)
  key   <- vapply(toks, function(t) paste(t$colour, t$style %||% ""), character(1))
  order_by <- order(vapply(toks, function(t) as.integer(!tx_empty(t$style)), integer(1)),
                    vapply(toks, function(t) t$colour, character(1)))
  groups <- unique(key[order_by])

  rules <- lapply(groups, function(k) {
    g <- toks[key == k]
    t <- g[[1]]
    hex <- tx_hex(t$colour, mode)
    face <- c("bold", "italic", "underline")[c(tx_style_flag(t$style, "bold"),
                                               tx_style_flag(t$style, "italic"),
                                               tx_style_flag(t$style, "underline"))]
    settings <- list(foreground = hex)
    if (length(face)) settings$fontStyle <- paste(face, collapse = " ")
    list(name  = paste0("txtheme ", t$colour, if (length(face)) paste0(" ", face[1])),
         scope = sort(unique(vapply(g, function(x) x$tm_scope, character(1)))),
         settings = settings)
  })

  out <- list(
    "_comments" = list(
      "GENERATED by txtheme::build_theme() from R/aaa-palette.R -- do not edit.",
      paste0("Paste the `textMateRules` array below into settings.json, under ",
             "editor.tokenColorCustomizations. Editor settings have no include mechanism, so this ",
             "one step is a paste by construction."),
      paste0("The editor's own foreground is a workbench colour, not a token scope: set it with ",
             "workbench.colorCustomizations, editor.foreground = ", tx_hex("ink", mode), ".")),
    textMateRules = rules)
  strsplit(tx_json(out), "\n", fixed = TRUE)[[1]]
}
