# PURPOSE: the `_brand.yml` writers -- the unified light/dark file Quarto auto-discovers, and the
#   single-mode one for the explicit `brand: {light:, dark:}` form.
# ROLE: layer A's artifact. It is what makes the palette readable by something that is not a
#   stylesheet -- a Quarto project, brand.yml's R side, or the next tool that learns the format.
# KEY CONSTRAINTS:
#   - Hand-rolled YAML, ~20 lines, for the same reason as the JSON (see R/aaa-grid.R). EVERY hex is
#     quoted: `#` opens a comment in YAML, so an unquoted colour is silently the empty string.
#   - The unified file is the primary artifact and needs NO `brand:` key from the consumer -- Quarto
#     auto-discovers a `_brand.yml` at a project root. An extension CANNOT set `brand:` for its
#     consumer (that key is resolved from project/document metadata, not from a format's render
#     defaults), so a file at the root is not a fallback here, it is the mechanism.
#   - ⚠ A `color.palette` ENTRY IS A SINGLE STRING -- Quarto's schema refuses `{light:, dark:}` there
#     outright ("The value must instead be a string", verified on 1.10.18). A ROLE does take the two.
#     So the unified file states, per mode, the roles as LITERAL HEXES, and names in the palette only
#     the colours that are the same in both modes. Every line of it is then true in both modes, which
#     a palette written from one half would not be.
#   - THE PALETTE'S NAMES ARE A NAMESPACE QUARTO SHARES. A `color.palette` entry named after a brand
#     ROLE is promoted to that role, in BOTH modes and with no message. R/zzz-checks.R refuses such
#     a name at load; the colour that paints links is called `accent` for exactly this reason.
# See: R/aaa-palette.R for TX_BRAND and BRAND_ROLES, dev/design.md sections 2-3 for what each
# consumer reads.

tx_yaml_hex <- function(x) paste0('"', x, '"')

# The colours that are the SAME in every mode -- the ten annotation hues, the note and its ink. They
# are the ones a document names in prose (`var(--brand-concept)`), and the only ones a single-string
# palette entry can state without lying in one mode or the other.
tx_mode_free <- function() {
  Filter(function(nm) length(unique(vapply(TX_MODES, tx_hex, character(1), colour = nm))) == 1L,
         names(TX_PALETTE))
}

tx_brand_palette <- function(names_, mode) {
  hex <- vapply(names_, tx_hex, character(1), mode = mode)
  paste0("    ", names_, ": ", tx_yaml_hex(hex))
}

#' The unified brand file
#'
#' One `_brand.yml`: the semantic roles per mode, and the mode-independent colours by name -- the
#' shape Quarto auto-discovers at a project root with no YAML at all on the consumer's part.
#'
#' @return A character vector of lines.
#' @noRd
emit_brand_unified <- function() {
  free  <- tx_mode_free()
  have  <- Filter(tx_has_mode, TX_MODES)
  roles <- unlist(lapply(names(TX_BRAND), function(k) {
    hex <- vapply(have, tx_hex, character(1), colour = TX_BRAND[[k]]$colour)
    c(paste0("  ", k, ":"), paste0("    ", names(hex), ": ", tx_yaml_hex(hex)))
  }))
  c("# GENERATED by txtheme::build_theme() from R/aaa-palette.R -- do not edit.",
    "#",
    "# The unified brand: one file, a light and a dark value per role. Copy it to a Quarto project's",
    "# ROOT and write nothing -- `brand:` is auto-discovered from there. It must never sit under",
    "# `format: html:`; nested there it is silently ignored, the two stylesheets come out identical,",
    "# and none of these colours appear.",
    "#",
    "# WHY THE ROLES ARE HEXES AND THE PALETTE IS SHORT. A palette entry must be a single string --",
    "# Quarto's schema refuses `{light:, dark:}` there -- while a role takes both. So the roles are",
    "# stated per mode as literal colours, and the palette names only what is the SAME in both: the",
    "# annotation hues, which sit at medium OKLCH lightness by construction and clear either ground.",
    "# Those are also the ones a document actually names, as `var(--brand-concept)` and friends, in",
    "# both stylesheets and with no hex leaving txtheme.",
    "#",
    "# WARNING: the palette's NAMES share a namespace with the roles. An entry named after a role",
    "#   (link, primary, danger, ...) is promoted to that role in BOTH modes, silently -- which is",
    "#   why the blue is `accent` and not `link`. txtheme refuses such a name at load.",
    "#",
    "# The theme's own chrome is NOT here: _extensions/txtheme sets it as bootstrap SASS variables,",
    "# which is the half of the job a brand file cannot do.",
    "meta:",
    "  name: txtheme",
    "color:",
    "  palette:",
    tx_brand_palette(free, "dark"),
    roles)
}

#' The single-mode brand file
#'
#' The shape `brand.yml::read_brand_yml()` can actually parse: the R side of the spec rejects
#' `color.foreground: {light:, dark:}`, so a tool reading a brand file from R needs one file per
#' mode. Quarto reads it too, named explicitly under `brand: {dark: …}`. One mode means one value
#' per name, so here the WHOLE palette can be written, and the roles refer to it by name.
#'
#' @param mode The half to write.
#' @return A character vector of lines.
#' @noRd
emit_brand_single <- function(mode = "dark") {
  keep <- names(TX_PALETTE)
  roles <- vapply(names(TX_BRAND), function(k)
    paste0("  ", k, ": ", TX_BRAND[[k]]$colour), character(1))
  c("# GENERATED by txtheme::build_theme() from R/aaa-palette.R -- do not edit.",
    "#",
    paste0("# The ", mode, " half alone. Use this one where a reader cannot take `{light:, dark:}`:"),
    "# brand.yml's R side rejects that shape, and Quarto takes it named explicitly, as",
    paste0("# `brand: {", mode, ": _brand-", mode, ".yml}`. inst/brand/_brand.yml is the file to prefer."),
    "#",
    "# One mode means one value per name, so the WHOLE palette is here and the roles name it.",
    "meta:",
    "  name: txtheme",
    "color:",
    "  palette:",
    tx_brand_palette(keep, mode),
    roles)
}
